// Package instrument rewrite source file via applying patch functions to source functions, and merge file import paths.
// provide instrumentation patch function of specified signature below, and simply execute instrumentation tool,
// input source file will be rewritten.
package instrument

//import (
//	gonativectx "context"
//)

// general instrumentation function signature
// 	ProcessFunc(spanName string, hasCtx bool, ctx gonativectx.Context, args ...interface{})
//
// 	// spanName was generated by parser, if hasCtx was true, user can use provided function param ctx
// gonativectx is alias for go native context package, mainly for avoiding pkg name confliction.
// args represents args of the instrumented function, using interface{} other than any only for compatiblity.
// user can ignore any fields other than spanName, for example, define one instrumentation function which is not
// interested in ctx and function args
// 	ProcessFunc(spanName string, _ bool, _ gonativectx.Context, _ ...interface{})
